"""update_user_model

Revision ID: 300e1c4153ec
Revises: 4d7c16e6856f
Create Date: 2026-09-27 07:13:07.498617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300e1c4153ec'
down_revision: Union[str, Sequence[str], None] = '4d7c16e6856f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET is_activate = true WHERE is_activate IS NULL")

    # 2. Thêm server_default và đặt nullable=False
    op.alter_column(
        'users',
        'is_activate',
        existing_type=sa.BOOLEAN(),
        server_default=sa.text('true'),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET is_activate = NULL WHERE is_activate = true")
    op.alter_column(
        'users',
        'is_activate',
        existing_type=sa.BOOLEAN(),
        server_default=None,
        nullable=True
    )
    # ### end Alembic commands ###
