"""add_google_auth_and_email_verified_to_users

Revision ID: 4d7c16e6856f
Revises: 2ac5599a1353
Create Date: 2026-09-26 21:23:15.728627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7c16e6856f'
down_revision: Union[str, Sequence[str], None] = '2ac5599a1353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(), server_default='email', nullable=False))
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.alter_column('users', 'password_hashed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'password_hashed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_sub')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
